# User config
author: "Jascha"
tagline: "More about me"
description: "All about Jascha's GitHub"
keywords: "jascha"
email: "jascha@cryptocartel.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/jascha"
github: "https://github.com/jaschadub"

# Site config
baseurl: "/"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
